version: 1.3.{build}
configuration: Release
platform: Any CPU
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
install:
- ps: >-
    (new-object Net.WebClient).DownloadString("https://raw.github.com/madskristensen/ExtensionScripts/master/AppVeyor/vsix.ps1") | iex

    Vsix-IncrementVsixVersion ".\CPPCheckPlugin\source.extension.vsixmanifest" | Vsix-UpdateBuildVersion
before_build:
- cmd: nuget restore
build:
  verbosity: minimal
artifacts:
- path: .\CPPCheckPlugin\bin\**\*.vsix